name: circuit-workflow
on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**config.kibot.yml'
    branches:
    - main
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**/config.kibot.yml'

jobs:
  circuits:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        include:
        # list of circuits here
        # - dir: "'boneIO\ -\ input\ board_BBB'"
        #   filename: "'boneIO_input\ board_BBB'"
        - dir: 'boneIO\ -\ relay\ board\ 24x10A'
          filename: 'boneIO\ -\ relay\ board'
        # - dir: "'boneIO\ -\ relay\ board\ 24x16A'"
        #   filename: "'boneIO\ -\ relay\ board'"
        # - dir: "'boneIO\ -\ relay\ board\ 32x5A'"
        #   filename: "'boneIO\ -\ relay\ board\ 32x5A'"
        # - dir: "'boneIO\ -\ shield\ input\ board\ v0.2'"
        #   filename: "'shield\ input\ board\ v0.2'"
        # - dir: "'boneIO\ -\ shutter\ board\ 32x10A'"
        #   filename: "'boneIO\ -\ shutter\ board\ 32x10A'"
        # - dir: "'boneIO\ -\ SSR\ DIMMER'"
        #   filename: "'boneIO\ -\ SSR\ DIMMER'"

    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        # entrypoint: /github/workspace/entry.sh
        config: Circuit/config.kibot.yml
        dir: output
        board: `"'Circuit/${{matrix.dir}}/${{matrix.filename}}.kicad_pcb'"`
        schema: `"'Circuit/${{matrix.dir}}/${{matrix.filename}}.sch'"`
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
