name: circuit-main-workflow
on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**config.kibot.yml'
    branches:
    - main
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**/config.kibot.yml'

jobs:
  circuits:
    name: ${{matrix.circuit}}
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        circuit:
        # list of circuits here
        - 'boneIO_-_input_board_BBB/boneIO_input_board_BBB'
        - 'boneIO_-_relay_board_24x10A/boneIO_-_relay_board'
        - 'boneIO_-_relay_board_24x16A/boneIO_-_relay_board'
        - 'boneIO_-_relay_board_32x5A/boneIO_-_relay_board_32x5A'
        - 'boneIO_-_shield_input_board_v0.2/shield_input_board_v0.2'
        - 'boneIO_-_shutter_board_32x10A/boneIO_-_shutter_board_32x10A'
        - 'boneIO_-_SSR_DIMMER/boneIO_-_SSR_DIMMER'

    steps:
    - uses: actions/checkout@v2
    - name: rename circuits
      run: |
        find Circuit -name "* *" | awk '{ print length, $0 }' | sort -nr -s | cut -d" " -f2- | while read f; do base=$(basename "$f"); newbase="${base// /_}"; mv "$(dirname "$f")/$(basename "$f")" "$(dirname "$f")/$newbase"; done
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: Circuit/config.kibot.yml
        dir: output
        schema: 'Circuit/${{matrix.circuit}}.sch'
        board: 'Circuit/${{matrix.circuit}}.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output

  update-wiki:
    name: update schemats on wiki
    needs: circuits
    if: ${{ github.ref == 'refs/pull/1/merge'}}
    # if: ${{ github.ref == 'refs/tags/master'}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: output
    - name: echo
      run: |
        echo "${{github.actor}}"
        echo "${{toJSON(github)}}"
    - name: add output pdf to wiki
      run: |
        git config --local user.email "{{$github.actor}}}""
        git add *-schematic.pdf
        git commit -m "update schemats from master@${{github.ref}}"
        git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.wiki.git"
