name: circuit-pr-workflow
on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**config.kibot.yml'
    branches:
    - main
  # pull_request:
  #   paths:
  #     - '**.sch'
  #     - '**.kicad_pcb'
  #     - '**/config.kibot.yml'

jobs:
  circuits:
    name: ${{matrix.circuit}}
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        circuit:
        # list of circuits here
        - 'Circuit/boneIO_-_input_board_BBB/boneIO_input_board_BBB'
        - 'Circuit/boneIO_-_relay_board_24x10A/boneIO_-_relay_board'
        - 'Circuit/boneIO_-_relay_board_24x16A/boneIO_-_relay_board'
        - 'Circuit/boneIO_-_relay_board_32x5A/boneIO_-_relay_board_32x5A'
        - 'Circuit/boneIO_-_shield_input_board_v0.2/shield_input_board_v0.2'
        - 'Circuit/boneIO_-_shutter_board_32x10A/boneIO_-_shutter_board_32x10A'
        - 'Circuit/boneIO_-_SSR_DIMMER/boneIO_-_SSR_DIMMER'

    steps:
    - uses: actions/checkout@v2
    - name: rename circuits
      run: |
        find Circuit -name "* *" | awk '{ print length, $0 }' | sort -nr -s | cut -d" " -f2- | while read f; do base=$(basename "$f"); newbase="${base// /_}"; mv "$(dirname "$f")/$(basename "$f")" "$(dirname "$f")/$newbase"; done
    - uses: INTI-CMNB/KiBot@v1
      with:
        config: Circuit/config.kibot.yml
        dir: output
        schema: '${{matrix.circuit}}.sch'
        board: '${{matrix.circuit}}.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
